In [1]:
import sys
import torch as tc
import pandas as pd

sys.path.append("../")
from src.implicit_finite_diff import imp_finite_difference

In [2]:
f_grid = imp_finite_difference(0.1, 0, 0.4, 50, 0.4167, 5, 0.04167, eu_am = "American")
f_price = f_grid.create_grid()

inveresed
tensor([4.9793e+01, 6.1581e-02, 5.4786e-04, 1.2245e-05, 4.9782e-07, 3.1224e-08,
        2.7311e-09, 3.1116e-10, 4.3965e-11, 7.4265e-12, 1.4581e-12, 3.2541e-13,
        8.1106e-14, 2.2252e-14, 6.6412e-15, 2.1350e-15, 7.3312e-16, 2.6689e-16,
        1.0204e-16, 3.9937e-17, 1.4053e-17])
tensor([4.9586e+01, 1.2225e-01, 1.6195e-03, 4.7735e-05, 2.3919e-06, 1.7706e-07,
        1.7735e-08, 2.2633e-09, 3.5224e-10, 6.4678e-11, 1.3659e-11, 3.2514e-12,
        8.5825e-13, 2.4792e-13, 7.7519e-14, 2.5998e-14, 9.2797e-15, 3.5000e-15,
        1.3817e-15, 5.5582e-16, 1.9941e-16])
tensor([4.9380e+01, 1.8203e-01, 3.1918e-03, 1.1633e-04, 6.8987e-06, 5.8616e-07,
        6.5892e-08, 9.2760e-09, 1.5712e-09, 3.1063e-10, 7.0020e-11, 1.7662e-11,
        4.9107e-12, 1.4866e-12, 4.8506e-13, 1.6913e-13, 6.2558e-14, 2.4379e-14,
        9.9134e-15, 4.0896e-15, 1.4934e-15])
tensor([4.9175e+01, 2.4092e-01, 5.2428e-03, 2.2686e-04, 1.5483e-05, 1.4797e-06,
        1.8382e-07, 2.8206e-08, 5.1500e-09, 1.0878e-09,

/Users/elvis/Desktop/School/research/option_pricing/notebook/../src/implicit_finite_diff.py:61: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  f[-1,:] = tc.tensor([tc.max(tc.tensor(self.K - S), tc.tensor(0.)) for S in self.Ss])


In [3]:
f_price

tensor([[4.8163e+01, 5.2258e-01, 2.1963e-02, 1.6552e-03, 1.8151e-04, 2.6136e-05,
         4.6441e-06, 9.7664e-07, 2.3590e-07, 6.3996e-08, 1.9163e-08, 6.2474e-09,
         2.1932e-09, 8.2159e-10, 3.2597e-10, 1.3611e-10, 5.9475e-11, 2.7023e-11,
         1.2620e-11, 5.8466e-12, 2.3112e-12],
        [4.8364e+01, 4.6791e-01, 1.7821e-02, 1.2332e-03, 1.2553e-04, 1.6930e-05,
         2.8388e-06, 5.6693e-07, 1.3074e-07, 3.4014e-08, 9.8058e-09, 3.0880e-09,
         1.0502e-09, 3.8208e-10, 1.4755e-10, 6.0087e-11, 2.5651e-11, 1.1407e-11,
         5.2255e-12, 2.3826e-12, 9.3184e-13],
        [4.8566e+01, 4.1243e-01, 1.4059e-02, 8.8452e-04, 8.2902e-05, 1.0402e-05,
         1.6368e-06, 3.0894e-07, 6.7741e-08, 1.6843e-08, 4.6603e-09, 1.4139e-09,
         4.6470e-10, 1.6385e-10, 6.1471e-11, 2.4371e-11, 1.0149e-11, 4.4111e-12,
         1.9795e-12, 8.8725e-13, 3.4301e-13],
        [4.8768e+01, 3.5611e-01, 1.0696e-02, 6.0435e-04, 5.1642e-05, 5.9804e-06,
         8.7719e-07, 1.5562e-07, 3.2291e-08, 7.6416e

In [4]:
pd.DataFrame(f_price.numpy()).transpose().iloc[::-1].round(2)

0          1      2      3          4      5          6      7   \
20   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
19   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
18   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
17   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
16   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
15   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
14   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
13   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
12   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
11   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
10   0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
9    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
8    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
7    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
6    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
5    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
4    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
3    0.00   0.000000   0.00   0.00   0.000000   0.00   0.000000   0.00   
2    0.02   0.020000   0.01   0.01   0.010000   0.01   0.000000   0.00   
1    0.52   0.470000   0.41   0.36   0.300000   0.24   0.180000   0.12   
0   48.16  48.360001  48.57  48.77  48.970001  49.18  49.380001  49.59   

           8     9          10  
20   0.000000   0.0   0.000000  
19   0.000000   0.0   0.000000  
18   0.000000   0.0   0.000000  
17   0.000000   0.0   0.000000  
16   0.000000   0.0   0.000000  
15   0.000000   0.0   0.000000  
14   0.000000   0.0   0.000000  
13   0.000000   0.0   0.000000  
12   0.000000   0.0   0.000000  
11   0.000000   0.0   0.000000  
10   0.000000   0.0   0.000000  
9    0.000000   0.0   0.000000  
8    0.000000   0.0   0.000000  
7    0.000000   0.0   0.000000  
6    0.000000   0.0   0.000000  
5    0.000000   0.0   0.000000  
4    0.000000   0.0   0.000000  
3    0.000000   0.0   0.000000  
2    0.000000   0.0   0.030000  
1    0.060000   0.0   0.580000  
0   49.790001  50.0  47.959999